import { Globe, Server, FileText, Send } from "lucide-react";

export const PROJECTS = [
  {
    id: "01",
    title: "GEN-AI.WEB",
    tag: "FRONT-END",
    category: "personal",
    desc: "Interface web do ecossistema Gen-AI com design system próprio. Fluxo completo de autenticação (login, reset de senha), dashboard com CRUD de usuários e fornecedores, guard de autenticação JWT e testes unitários + E2E.",
    stack: ["React", "TypeScript", "Vite", "Chakra UI", "TanStack Router", "React Query", "Axios", "Zod"],
    stars: 0,
    color: "#4A6FA5",
    icon: Globe,
    githubUrl: "https://github.com/LeonardoSodre20/gen-ai-web",
    cover: "/images/gen-ai-web.png",
  },
  {
    id: "02",
    title: "GEN-AI.BACKEND",
    tag: "BACK-END",
    category: "personal",
    desc: "API RESTful do ecossistema Gen-AI com NestJS e MongoDB. Autenticação JWT com rotação de refresh tokens, CRUD de usuários com validação robusta, TypeORM e testes e2e com Testcontainers.",
    stack: ["NestJS", "TypeScript", "MongoDB", "TypeORM", "JWT", "Docker", "Vitest", "SWC"],
    stars: 0,
    color: "#E0234E",
    icon: Server,
    githubUrl: "https://github.com/LeonardoSodre20/gen-ai-backend",
    cover: "/images/gen-ai-backend.png",
  },
  {
    id: "03",
    title: "LAMECOMEX.LANDING",
    tag: "FRONT-END",
    category: "professional",
    company: "LameComex",
    desc: "Landing page institucional da LameComex, empresa de logística internacional. Site bilíngue (PT/EN) com design responsivo, carrossel de serviços, categorias de produtos e integração com WhatsApp. Desenvolvida com React 19 e Tailwind CSS v4.",
    stack: ["React", "TypeScript", "Vite", "Tailwind CSS", "TanStack Router", "i18next", "Swiper"],
    stars: 0,
    color: "#FCC50D",
    icon: FileText,
    demoUrl: "https://www.lamecomex.com/",
    cover: "/images/lamecomex-landing.png",
  },
  {
    id: "04",
    title: "DISPAROPRO",
    tag: "FULLSTACK",
    category: "professional",
    company: "DisparoPRO",
    desc: "Plataforma de comunicação multicanal para disparo de WhatsApp, SMS, RCS e voz em massa. Arquitetura em monorepo com Turborepo, CI/CD automatizado com GitHub Actions, design system com ShadcnUI e containerização com Docker. Atende mais de 5 mil clientes.",
    stack: ["TypeScript", "React Query", "Tailwind CSS", "ShadcnUI", "Turborepo", "Docker", "GitHub Actions"],
    stars: 0,
    color: "#10B981",
    icon: Send,
    demoUrl: "https://disparopro.com.br/",
    cover: "/images/disparopro.png",
  },
] as const;
